export {default as Header} from '../components/header/header'
export {default as Hero} from '../components/main/hero'
export {default as Container} from '../components/container'
export {default as Content} from '../components/content/Content'
export {default as Step} from '../components/step/step'
export {default as FastBusinessLoan} from '../components/content/fastBusinessLoan'
export {default as MoneyForBusiness} from '../components/content/moneyForBusiness'